version: '3'
name: "meu-devocionario"
services:
  mongo:
    container_name: database-mongo
    image: mongo:latest
    restart: always
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGODB_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGODB_PASSWORD
      MONGO_INITDB_DATABASE: $MONGODB_DATABASE
    volumes:
      - ./data/mongo:/data/db
    ports:
      - 27017:27017
    networks:
      - default

networks:
  default:
    name: web
    external: true
