name: Setup AWS

on:
  workflow_call:
    outputs:
      registry_encrypted:
        description: "ECR Registry Encrypted"
        value: ${{ jobs.setup-aws.outputs.registry_encrypted }}
      ecr_username:
        description: "ECR User Name"
        value: ${{ jobs.setup-aws.outputs.ecr_username }}
      ecr_password:
        description: "ECR User Password"
        value: ${{ jobs.setup-aws.outputs.ecr_password }}

jobs:
  setup-aws:
    runs-on: ubuntu-latest

    environment: prod
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Setup AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/meu-devocionario-ci-cd
          aws-region: ${{ secrets.AWS_ECR_REGION }}

      - name: Setup Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Replace AWS Region hyphens
        run: |
          AWS_ECR_REGION=$(echo ${{ secrets.AWS_ECR_REGION }} | sed 's/-/_/g')
          echo "AWS_ECR_REGION=$AWS_ECR_REGION" >> $GITHUB_ENV

      - name: Encode registry
        env:
          SECRET: ${{ secrets.SECRET_PASSPHRASE }}
        id: login-secrets
        shell: bash
        run: |
          ecr_registry="${{ steps.login-ecr.outputs.registry }}"
          echo "::add-mask::$ecr_registry"
          ecr_registry_encrypted=$(gpg --symmetric --batch --passphrase "$SECRET" --output - <(echo "$ecr_registry") | base64 -w0)
          echo "registry_encrypted=$ecr_registry_encrypted" >> "$GITHUB_OUTPUT"

    outputs:
      registry_encrypted: ${{ steps.login-secrets.outputs.registry_encrypted }}
      ecr_username: ${{ steps.login-ecr.outputs[format('docker_username_{0}_dkr_ecr_{1}_amazonaws_com', secrets.AWS_ACCOUNT_ID, env.AWS_ECR_REGION)] }}
      ecr_password: ${{ steps.login-ecr.outputs[format('docker_password_{0}_dkr_ecr_{1}_amazonaws_com', secrets.AWS_ACCOUNT_ID, env.AWS_ECR_REGION)] }}

 